---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-alert-config
  namespace: monitoring
spec:
  encryptedData:
    config.yml: AgAOrTgAxwSrWxbty4x5IFKV7tBjIhCu1w1irKGqQmiOoR20M9jzZzpFR/44ONWb3VZRz5bZfK0IXB9TFuqHZA8+QzBh8m6FP2VqEgzx7LSmic5PUSthd5aQyTWS9dHaqQXkWTVJqcL/4NOuPAk6i8iKFViR4R2A2lm6hhKHiMHVjzbxgivdDnrMUB4TXKoHUKEKZX5BZ/WREf/NcXdV79R8ZraUQRBaGb0bEtZSze24gghzicbhq12hnWPe+zy4SIiLZM5HijEbdhHm+KNGBoIWIt2mXB70/5P8a8DMcb3VrrLQuhEi9A9HEu/66z6AyMuNNW7STHySft3mPHExsV4MHeWNU5xyrzF5WV9f7wbvjRKr76thDx6TceXzaaMDnVoaXwdJII9Jr1jyE4/2FqafMmsuGHuJfcMBAcbgioGrAHREozyJjfwGxhtXdZRNE/ZjgDCQ8Yv5GHP2I9O8NLNo4m9/UpSWGcV/8ZAjGPQeOgznB47wAlCm3TRJFNFhsUF1FaNxhTsNKsSrKMX1Wqsc1K73mnRfbvHlvWGdfc8g4Mo+2ZQhCc5kv8PHB7ba0w+faxnTUX2sezsXLIGD+1S/bySaXi8SjW/UkrMtzqbszx0FeMUbV6JsyO7GDsMFExjlEKllwtZvUqhGzMIyhKrYrmalcmAMkv5n/mYv0MtifDNBuilQV/c1eXeu+cN6fI6vJV4By2i8aPezApgiMmEr59kUGm0sRW4VOzxVJP3aqL6k/clRci4QrAopgvsAb0XPgoDGl2VwJc525wKVjF5dGJB3AyQWacu18QhBnArMzhWy25vA23IKCnER6wCY20/2lGSrYwDMwpAYPgbOQGZIoDGW7vhxtD53Ll/Yyc4QV/QquTBAWqFNdQaPNaNkmOFDqviWnkwI6vdnUQv9Rw1MgQZAOTEqGkd7vPEb7JSdWncvqxKoh8JcWSBqiwMgbggNtDqUiprE8onrOzBOFqbj31ybl6/xATHWGSLKV7GShePusSjbV6m3Nl4eXx6PY9bk5i5U7tTssYub+uVQ+kz1PrTOxNPECfl6L1ujRosUyVk5BTSDWDWdcS+hRJbwZ5BbJRr9xQf2GNENFBtmT5mnj7pMTCnCg1KzOkQ6AgpB90mFjSqOVElt+zKJiA3n6wB+nHLl4LxVH+mg9VmA6NIpTEkYCQynsckkW/G8Hc1WAe8jFF+c4ZounWi5sWf0EQPKs0h7dPzB+Z7OW3xIxIkBLOqVWscNmIziYj0mmdGiL5zEHbg3pdrVaw1Q29i6uDs9Kt7FLnMetjhJ9isNLiYsA69ZFUTR+1LX2jW5j/ZATe7Zm8mKZwj8ETtKxW12SWVDEPJYkfs05oIAplHxMPhjoo8/8kazLJHuVWUxPW3bMLBDJk/BT6LgeclSywzUHrE2TiYrRA9yHUPd105X5WCu9wp5bP+ygXAOhEGMxk4r3GS0ifo=
  template:
    metadata:
      creationTimestamp: null
      name: secret-alert-config
      namespace: monitoring
    type: Opaque
