apiVersion: v1
kind: Pod
metadata:
  name: alpine-default
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine:3.12
    command:
        - sleep
        - "3600"
    imagePullPolicy: IfNotPresent
