apiVersion: v1
kind: Pod
metadata:
  name: failed-pod
  labels:
    appss: failed-pod
spec:
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine:3.12
    command:
        - sleep
        - "1"
        - exit 1
    imagePullPolicy: IfNotPresent
